#!/bin/bash
# Description: This script is used to backup important files to github 
# Run on exit of system

#!/bin/bash

run_python_script() {
    local repo_path="$1"
    local script_path="$2"
    echo "Repository path: $repo_path"
    echo "Script path: $script_path"
    git -C "$repo_path" status -s | grep '^M ' | cut -c 4- | xargs -I {} python3 "$script_path" "$repo_path" '{}'
}

update_git_repo() {
    local repo_path="$1"
    local commit_msg="$2"
    git -C "$repo_path" add .
    git -C "$repo_path" commit -m "$commit_msg"
    git -C "$repo_path" push
}
update_git_repo_u() {
    local repo_path="$1"
    local commit_msg="$2"
    git -C "$repo_path" add -u
    git -C "$repo_path" commit -m "$commit_msg"
    git -C "$repo_path" push
}

main() {
    local base_path="/home/benjrise"
    local remote_scene="$base_path/Documents/latex/remote-scene"
    local obsidian_path="$base_path/Data/Obsidian/ml-notes"
    local second_brain_path="$base_path/Data/Obsidian/second-brain"
    #
    # Update various configurations and dotfiles
    echo "Backing up: $base_path/.config/nvim/"
    update_git_repo "$base_path/.config/nvim/" "nvim update"
    echo "Backing up : $base_path/.dotfiles/"
    update_git_repo "$base_path/.dotfiles/" ".dotfiles update"
    echo "Backing up $remote_scene"
   update_git_repo "$remote_scene" "remote-scene update"

    # Update base repository
    echo "Backing up home directory dotfiles"
    git -C "$base_path" add -u
    git -C "$base_path" add .scripts
    git -C "$base_path" commit -m ".config update"
    git -C "$base_path" push

    # Update Obsidian notes
    echo "Backing up obsidian notes"
    git -C "$obsidian_path" add -u
    # run_python_script "$obsidian_path" "$base_path/.scripts/mod-date/add-modified-date.py"
    update_git_repo "$obsidian_ipath" "auto-backup"


    # Update second brain
    echo "Backing up second brain"
    cd "$second_brain_path" || exit
    git add .
    # run_python_script "$second_brain_path" "$base_path/.scripts/quotes.py"
    update_git_repo "$second_brain_path" "auto-backup"
}

main

