#!/bin/bash
# Description: This script is used to backup important files to github 
# Run on exit of system

run_python_script() {
    local repo_path=$1
    local script_path=$2
    echo $repo_path
    echo $script_path
    git -C $repo_path status -s | grep '^M ' | cut -c 4- | xargs python3 $script_path $repo_path
}

update_git_repo() {
    local repo_path=$1
    local commit_msg=$2
    git -C $repo_path pull
    git -C $repo_path add .
    git -C $repo_path commit -m "$commit_msg"
    git -C $repo_path push
}

main(){
   local base_path="/home/benjrise"
   local obsidian_path="$base_path/Data/Obsidian/ml-notes"
   local second_brain_path="$base_path/Data/Obsidian/second-brain"
   cd $base_path
   git -C /home/benjrise/ add -u 
   git -C /home/benjrise/ add .scripts
   git -C /home/benjrise/ commit -m ".config update"
   git -C /home/benjrise/ push
   #
   git -C $obsidian_path add -u
   run_python_script $obsidian_path "$base_path/.scripts/mod-date/add-modified-date.py"
   update_git_repo $obsidian_path "auto-backup"
   update_git_repo "$base_path/.config/nvim/" "nvim update"
   update_git_repo "$base_path/.dotfiles/" ".dotfiles update"

   cd /home/benjrise/Data/Obsidian/second-brain/
   git add .
   run_python_script $second_brain_path "$base_path/.scripts/quotes.py"
   update_git_repo $second_brain_path "auto-backup"
}
main
